#from lincomtest import *
import matplotlib.pyplot as plt
import numpy as np
#plt.hist(diff, bins=np.logspace(-1, 1.0, 100))
#plt.show()
#plt.plot(newEdt[0], 'b.')


#close open plots
plt.close('all')
#import np arrays of diff for different periods
ydiff =np.load('yeardiff.npy')
mdiff = np.load('monthdiff.npy')
ddiff = np.load('daydiff.npy')
bigerrday = min(ddiff[80])

#create max and min difference data for use in residual plots
##difference in microseconds (all points) Period of Yyar
ydiffmics = np.multiply(ydiff, 10**6)
#min and max difference  in microseconds, 1 each per vector 
minydiff = np.amin(ydiffmics.T, 0)
maxydiff =np.amax(ydiffmics.T, 0)
useydiff = np.array((minydiff, maxydiff)).T

#Period of 30 days
mdiffmics = np.multiply(mdiff, 10**6)
#min and max difference  in microseconds, 1 each per vector 
minmdiff = np.amin(mdiffmics.T, 0)
maxmdiff =np.amax(mdiffmics.T, 0)
usemdiff = np.array((minmdiff, maxmdiff)).T

#Period of 1 day
ddiffmics = np.multiply(ddiff, 10**6)
#min and max difference  in microseconds, 1 each per vector 
minddiff = np.amin(ddiffmics.T, 0)
maxddiff =np.amax(ddiffmics.T, 0)
useddiff = np.array((minddiff, maxddiff)).T


##Histogram of residuals, currently ugly bins but will sort!
#
fig1= plt.figure()
ax1 = fig1.add_subplot(111)
ax1.hist(np.ravel(useydiff),bins = 10)
fig1.suptitle('Histogram of Max and Min Residuals for Period of a Year')
ax1.set_xlabel('Emitdt- Model (Microseconds)')
ax1.set_ylabel('Frequency')
plt.grid()


#scatter plot of maximum and minimum residuals, exactly how i want it!
fig2 = plt.figure()
ax2 = fig2.add_subplot(111)
ax2.plot(useydiff, 'ro')
fig2.suptitle('Plot of Max and Min Residuals for Period of a Year')
ax2.set_xlabel('Number of Corresponding Time Difference Vector ')
ax2.set_ylabel('Residuals (Microseconds)')
plt.grid()

##plot individual
#fig3 = plt.figure()
#ax3 = fig3.add_subplot(111)
#ax3.plot(ydiffmics[0], 'r-')
#fig3.suptitle('Plot of First Set of Residuals for Model Generated by Random Time and Source Vectors and Start Time (Within Acceptable Ranges) ')
#ax3.set_xlabel('Edt Entry ')
#ax3.set_ylabel('Residuals (microseconds)')
#plt.grid()
#
#
#
##plot individual
#fig4 = plt.figure()
#ax4 = fig4.add_subplot(111)
#ax4.plot(ydiffmics[99], 'b-')
#fig4.suptitle('Plot of Last Set of Residuals for Model Generated by Random Time and Source Vectors and Start Time (Within Acceptable Ranges) ')
#ax4.set_xlabel('Edt Entry ')
#ax4.set_ylabel('Residuals (microseconds)')
#plt.grid()
#
##plot individual
#fig5 = plt.figure()
#ax5 = fig5.add_subplot(111)
#ax5.plot(ydiffmics[49], 'g-')
#fig5.suptitle('Plot of 49th Set of Residuals for Model Generated by Random Time and Source Vectors and Start Time (Within Acceptable Ranges) ')
#ax5.set_xlabel('Edt Entry ')
#ax5.set_ylabel('Residuals (microseconds)')
#plt.grid()
##display plots
#p

##Histogram of residuals, currently ugly bins but will sort!
#
fig6= plt.figure()
ax6 = fig6.add_subplot(111)
ax6.hist(np.ravel(usemdiff),bins = 10)
fig6.suptitle('Histogram of Max and Min Residuals for Period of a Month')
ax6.set_xlabel('Emitdt- Model (Microseconds)')
ax6.set_ylabel('Frequency')
plt.grid()


#scatter plot of maximum and minimum residuals, exactly how i want it!
fig7 = plt.figure()
ax7 = fig7.add_subplot(111)
ax7.plot(usemdiff, 'rx')
fig7.suptitle('Plot of Max and Min Residuals for Period of a Month')
ax7.set_xlabel('Number of Corresponding Time Difference Vector ')
ax7.set_ylabel('Residuals (Microseconds)')
plt.grid()

##Histogram of residuals, currently ugly bins but will sort!
#
fig8= plt.figure()
ax8 = fig8.add_subplot(111)
ax8.hist(np.ravel(useddiff),bins = 10)
fig8.suptitle('Histogram of Max and Min Residuals for Period of a Day')
ax8.set_xlabel('Emitdt- Model (Microseconds)')
ax8.set_ylabel('Frequency')
plt.grid()


#scatter plot of maximum and minimum residuals, exactly how i want it!
fig9 = plt.figure()
ax9 = fig9.add_subplot(111)
ax9.plot(useddiff, 'r.')
fig9.suptitle('Plot of Max and Min Residuals for Period of a Day',  fontsize = 18)
ax9.set_xlabel('Number of Corresponding Time Difference Vector ', fontsize = 16)
ax9.set_ylabel('Residuals (Microseconds)', fontsize = 16)
plt.grid()


fig10 = plt.figure()
ax10 = fig10.add_subplot(111)
ax10.hist((np.ravel(usemdiff), np.ravel(useydiff)), bins = 10, label = ['Month', 'Year'], color = ['r', 'b'])
fig10.suptitle('Histogram of Residuals for Periods of a Month and a Year', fontsize = 18)
ax10.set_xlabel('Residuals (Microseconds)', fontsize = 16)
ax10.set_ylabel('Frequency', fontsize = 16)
plt.legend()

fig11 = plt.figure()
ax11 = fig11.add_subplot(111)
ax11.plot(range(100), usemdiff.T[0],'rx', label = 'Month')
ax11.plot(range(100), usemdiff.T[1],'rx')
ax11.plot(range(100), useydiff.T[0], 'b.', label = 'Year')
ax11.plot(range(100), useydiff.T[1], 'b.')
fig11.suptitle('Plot of Residuals for Period of a Month and a Year', fontsize = 18)
ax11.set_xlabel('Number of Corresponding Time Difference Vector ',  fontsize = 16)
ax11.set_ylabel('Residuals (Microseconds)', fontsize = 16)
plt.grid()
plt.legend(numpoints=1)
plt.show()