from lincomtest import *
import matplotlib.pyplot as plt
import numpy as np
#plt.hist(diff, bins=np.logspace(-1, 1.0, 100))
#plt.show()
#plt.plot(newEdt[0], 'b.')

diffmics = np.multiply(diff, 10**6)
##Histogram of residuals, currently ugly bins but will sort!
#
fig1= plt.figure()
ax1 = fig1.add_subplot(111)
ax1.hist(diffmics, range = (np.amin(diffmics),np.amax(diffmics)))
fig1.suptitle('Histogram of Residuals for Model Generated by Random Time and Source Vectors and Start Time (Within Acceptable Ranges) ')
ax1.set_xlabel('Emitdt- Model (microseconds)')
ax1.set_ylabel('Frequency')
plt.grid()

##scatter plot of residuals
#plt.scatter(np.linspace(-1, 1, np.size(diff)),diff)
fig2 = plt.figure()
ax2 = fig2.add_subplot(111)
ax2.plot(diffmics, 'bx')
fig2.suptitle('Plot of Residuals for Model Generated by Random Time and Source Vectors and Start Time (Within Acceptable Ranges) ')
ax2.set_xlabel('Edt Entry ')
ax2.set_ylabel('Residuals (microseconds)')
plt.grid()

#display plots
plt.show()
